id: PEB43B68D
initial_creation_type: input
source_metadata:
  title: Dudjom Rinpoche Series
  language: de
  description: 'We present the following texts by Kyabje Dudjom Rinpoche Jikdral Yeshe
    Dorje (bdud ''joms ''jigs bral ye shes rdo rje, 1904–1987), the renowned yogi
    and scholar and first appointed head of the Nyingma school in exile:'
  volume:
    6261a80bf2a4423c90a76ee82596291b:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Advice
    011a3e760ff74dbb9151f1187b2ea013:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Benefits
    20ad187eeebe4a42b132fd9b8a395a3f:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    16b975cab6984022946a6301ef890d4f:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    bdfcf18334af494ca7b4c5254c0ccaa6:
      title: Concise Consecration
      parent: Consecration
    4128c62ffe2548b3af12b01a4b611f8e:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Dharma Protectors
    4248068eb2b048828e02a091e5b50bd8:
      title: Dzogchen Aspiration Prayer
      parent: Dzogchen
    c5bcecbd79ce486c88cacabd4989f01a:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Dzogchen
    b7393bea5c45446aab0730f164daf72a:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Dzogchen
    39b3aeca6d4d4fa4aa89108bade359b3:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Guru Rinpoche Prayers
    a02306c11d0b49e8bbd59abac23b3d46:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Guru Rinpoche Prayers
    da538b9112b54220bca9ce37f6891c45:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Guru Rinpoche Prayers
    4157bd19484e4e9da8a546b5cb6e8592:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Guru Rinpoche Prayers
    3dc04efa66ae4f6abe60ac8cd5b30fbc:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Guru Rinpoche Prayers
    8a83eb8a418b447ea216464bcecde5e4:
      title: A Concise Lineage Prayer
      parent: Lineage Prayers
    620a764f98b14a9eb25ac19377605a95:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    2ec1792209fa418491428fd8b443ad99:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    afe9bb39b73f474bb67aa422e7a20884:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    59bdca845a344ca08b36031adc50b0b6:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    a28dc9cca84c47b0b8bb7523e66e5b99:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Long Life Prayers
    de02d91813b743ef97c6d1380a2c70da:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Ngöndro
    39915d5c981a402ebb1c42b1d41da0fa:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Ngöndro
    ccc46f9ebfb04b739d1f3d23d30f582b:
      title: Brief Red Sur Offering
      parent: Offering
    4241cebbd51d4fb0bf9055225a8726e4:
      title: Brief Sur Offering
      parent: Offering
    308fadb767d74deb98e9341558d85e0f:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayers
    8208939ea6a848598f3c8090b39ceb6e:
      title: Essence and Embodiment of All the Buddhas
      parent: Prayers
    c82d7f3a64d24ca38dbf68720690fbfa:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    85833dc44c4f4152a3a77984b1f19e4c:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Sādhanas
    2f7f60dbd9044a4784ca995735a0330b:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    1a3eff7da1ed430a98579a5a6f1bd765:
      title: A Daily Practice of Lama Sangdü
      parent: Sādhanas
    27707618c6284627aff456aa2e9ad953:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    fd2e1a8c33aa4726b0e28d93f9ff1278:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    7cecdb4e07504f1f837b551cc870c10f:
      title: Daily Practice of Dorje Gotrab
      parent: Sādhanas
    dab3eea33a394025a055d873fff0960a:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sādhanas
    17ea9fdae44f41f28bbffd34e8e8899d:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
    991cd401fe0d44b993cf3a9cd51d2c1f:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    4109664daa5f46c1a0aff186fd1c4a70:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    dc57565371774fa198cbbbf3dd4fdf39:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    ee43eb910cbd496f930d9daaab62e80e:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
    a44c9674b6904ccb87139691510a1fde:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
    054dcea9335c4c73818ada8aeaa2fa8d:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      parent: Sojong
    9bd4594bd0404da793d50b3ec3b88184:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Tsok
    40719d64eadb43cf99787e54db620d7a:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Tsok
    47d390fc66f34e04814b9376c243d850:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-02-28T23:10:30.048637'
last_modified_at: '2022-02-28T23:10:30.048640'
